#!/bin/bash
# vim:et:ft=sh:sts=2:sw=2
INSTALLER_HOME=".."
TEST_RUNNER_SHUNIT_VERSION=2.1.6
TEST_RUNNER_SHUNIT="$INSTALLER_HOME/external/shunit2-$TEST_RUNNER_SHUNIT_VERSION/src/shunit2"


run_installs () {
  return 0
}
